steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "europe-southwest1-docker.pkg.dev/$PROJECT_ID/conversation-manager/chatboteoi:$SHORT_SHA", ".",]
  - name: "gcr.io/cloud-builders/docker"
    args:
        ["push", "europe-southwest1-docker.pkg.dev/$PROJECT_ID/conversation-manager/chatboteoi:$SHORT_SHA"]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - "gcloud"
      - "run"
      - "deploy"
      - "chatbot-eoi"
      - "--image"
      - "europe-southwest1-docker.pkg.dev/chatboteoi/conversation-manager/chatboteoi:$SHORT_SHA"
      - "--region=europe-southwest1"
      - "--platform=managed"
      - "--allow-unauthenticated"
images:
  - "europe-southwest1-docker.pkg.dev/$PROJECT_ID/conversation-manager/chatboteoi:$SHORT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
